spring:
  application:
    name: PRODUCT-SERVICE-CONSUMER
  datasource:
   url: jdbc:mysql://localhost:3306/product_db
   username: root
   password: Incapp@12
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
